2025-08-03 22:34:43,117 Minimum price: 10, Maximum price: 350
2025-08-03 22:34:43,131 Preparing sklearn pipeline
2025-08-03 22:34:43,131 Fitting
2025-08-03 22:34:43,782 Scoring
2025-08-03 22:34:43,883 Score: 0.5714574367167663
2025-08-03 22:34:43,883 MAE: 33.46325896500654
2025-08-03 22:34:43,883 Exporting model
2025/08/03 22:34:43 WARNING mlflow.models.signature: Failed to infer the model signature from the input example. Reason: MlflowException("Unable to map 'object' type to MLflow DataType. object can be mapped iff all values have identical data type which is one of (string, (bytes or byterray),  int, float)."). To see the full traceback, set the logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)`. To disable automatic signature inference, set `signature` to `False` in your `log_model` or `save_model` call.
/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
Traceback (most recent call last):
  File "/home/dennis-grisham/D501_Project_1_NYC_Airbnb/src/train_random_forest/run.py", line 298, in <module>
    go(args)
  File "/home/dennis-grisham/D501_Project_1_NYC_Airbnb/src/train_random_forest/run.py", line 106, in go
    mlflow.log_artifacts("random_forest_dir")
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1020, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1188, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 538, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 60, in log_artifacts
    shutil.copytree(src=local_dir, dst=artifact_dir, dirs_exist_ok=True)
  File "/home/dennis-grisham/miniconda3/envs/mlflow-d20df18b17b0c54747eba2677649d2bbc0879a75/lib/python3.10/shutil.py", line 554, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 'random_forest_dir'